name: meditation_center
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  go_router: ^16.0.0
  provider: ^6.1.5
  another_flushbar: ^1.12.30
  flutter_easyloading: ^3.0.5
  cloud_firestore: ^6.0.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  cloudinary_sdk: ^5.0.0+1
  flutter_local_notifications: ^19.4.1
  lottie: ^3.3.1
  permission_handler: ^12.0.1
  dio: ^5.9.0
  path_provider: ^2.1.5
  saver_gallery: ^4.0.1
  device_info_plus: ^11.3.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.9.1
  firebase_messaging: ^16.0.1
  googleapis_auth: ^2.0.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env  
    - assets/logo/
    - assets/icons/
    - assets/jpg/
    - assets/video/
    - assets/lottie/
    - assets/app/app_icon.png
